title: Notepad
author:
  name: moses
description: Humble Programming Notes
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/vemqar" }
markdown: kramdown
header_pages:
  - about.md